# Generated by Django 4.0.4 on 2022-05-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_content', models.TextField()),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
