# Generated by Django 4.0.4 on 2022-05-26 19:26

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
