# Generated by Django 4.0.4 on 2022-05-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_alter_blogmodel_blog_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='blog_content',
            new_name='blogContent',
        ),
    ]
